[package]
name    = "lockdown"
version.workspace = true
edition.workspace = true

[dependencies]
usbmux         = { workspace = true }
plist          = { workspace = true }
serde          = { workspace = true }
thiserror      = { workspace = true }
rustls         = { version = "0.23", features = ["tls12"] }
rustls-pemfile = "2"

[dev-dependencies]
usbmux = { workspace = true }
plist  = { workspace = true }
