[package]
name    = "ios"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ios"
path = "src/main.rs"

[dependencies]
usbmux      = { workspace = true }
lockdown    = { workspace = true }
tunnel      = { workspace = true }
clap        = { workspace = true }
comfy-table = { workspace = true }
anyhow      = { workspace = true }
plist       = { workspace = true }
